### ISSUE TITLE
Which version of mmdet is used in this project？

### ISSUE THREAD

**Issue by Klawens** [sandylaker/efficientdet_mmdet#1]
Hi there! Which version of mmdet is used in this project?

**Comment by sandylaker** [comment]
mmdet 2.8. But I believe it is compatible with mmdet 2.0+ versions. P.S.: Due to limited computation resource that I have, the implementation is not tested on the MS-COCO2017 dataset yet. But according to the result on Pascal VOC07+12, the implementation should not be too far from the official one.
